### ISSUE TITLE
Paper Suggestion

### ISSUE THREAD

**Issue by ishan00** [gentaiscool/code-switching-papers#10]
Hello, this is a relevant paper for code-switching accepted at ACL-IJCNLP 2021

From Machine Translation to Code-Switching: Generating High-Quality Code-Switched Text
Ishan Tarunesh, Syamantak Kumar, Preethi Jyothi

https://aclanthology.org/2021.acl-long.245.pdf

**Comment by gentaiscool** [comment]
thanks for the suggestion. I approved the PR to add the paper.
