### ISSUE TITLE
Add Section for Datasets?

### ISSUE THREAD

**Issue by tnagar72** [gentaiscool/code-switching-papers#16]
I'm currently working on a project that requires a seed spanglish code-switched dataset and would love to see recommendations on where I could find these. Thank you!

**Comment by gentaiscool** [comment]
Hi @tnagar72 thank you for reaching out. I plan to have a big update the repo, including the latest papers using LLMs which is very relevant on current use cases. I found some cool papers in the last months and datasets creation using LLMs. I will let you know when the repo is updated! Stay tuned!
