### ISSUE TITLE
open source software for code switching

### ISSUE THREAD

**Issue by jwijffels** [gentaiscool/code-switching-papers#5]
thanks for this list
do you also have a list of interesting open source software tools for code switching (e.g written in C++/C+Java/Python/R?)

**Comment by gentaiscool** [comment]
hi @jwijffels 
Currently, you can find open source codes for code-switching papers, but not all of the authors release their code. If you have any interesting list of tools for code-switching, please let me know.  Probably, we can find a way to put it here.
Thank you.

**Comment by jwijffels** [comment]
I'll do some research to see in each paper if they refer to open code. But you probably already have such a list in your head no?

**Comment by gentaiscool** [comment]
Only very few authors released their code. If you found one, you can send me a pull request. I will also check.
Thanks @jwijffels
