### ISSUE TITLE
open source speech dataset for code switching

### ISSUE THREAD

**Issue by ragnarlbrok** [gentaiscool/code-switching-papers#6]
HI, I am unable to find any open source speech corpus related to mentioned papers. Can you list down some good open source speech datasets for code switching?

**Comment by gentaiscool** [comment]
hi @ragnarlbrok. I will add information about open source speech corpus to this repository. Thanks for your suggestion.

**Comment by ragnarlbrok** [comment]
Hi @gentaiscool, can you provide some links for code switching speech datasets here? currently, I am working with TTS generated datasets, need it in urgent for my experiments.

**Comment by gentaiscool** [comment]
Sorry I was very busy with other projects. Have you check the datasets from this competition https://www.microsoft.com/en-us/research/event/workshop-on-speech-technologies-for-code-switching-2020/ ? 

There is also another shared task prepared by Microsoft this year https://twitter.com/Ashish_Mittal1/status/1358664855616557061/photo/1

or if you have subscription to LDC, I recommend you to check https://catalog.ldc.upenn.edu/LDC2015S04, but this is not free. Hopefully it helps.

**Comment by ragnarlbrok** [comment]
@gentaiscool, thanks for providing links. I have checked LDC dataset already but unluckily not free.  for link https://www.microsoft.com/en-us/research/event/workshop-on-speech-technologies-for-code-switching-2020/  I am not able to find dataset download link. https://twitter.com/Ashish_Mittal1/status/1358664855616557061/photo/1 dataset is asking for password, I think, will need to register in competition for access. Hindi-English dataset is good for me, but Chinese-English dataset is on my priority. if you have some link for Chinese-English or Spanish-English, pls share them, it would be great.

**Comment by gentaiscool** [comment]
Hi @ragnarlbrok, I don't have the datasets that I can share with you currently. I suggested to try with the LDC dataset. They have ~200 hours data. If you are studying in a university, probably your uni has the access to LDC, you should check with the admin.

**Comment by ragnarlbrok** [comment]
Ok, thank you, @gentaiscool, for the information.
