### ISSUE TITLE
Synthetic Code-Mixed Data Generation

### ISSUE THREAD

**Issue by mohdsanadzakirizvi** [gentaiscool/code-switching-papers#7]
Paper - https://www.aclweb.org/anthology/2021.eacl-demos.24/
GitHub - https://github.com/microsoft/CodeMixed-Text-Generator

Hey, I recently worked on this and thought it might be useful to add it to the list. :)

**Comment by gentaiscool** [comment]
Sounds good! I can add it

**Comment by gentaiscool** [comment]
I just added your paper to the list :)
